### PR TITLE
Euler_totient.cpp

### PR DESCRIPTION
**Pull request by ishi0301**

### CODE REVIEW

**Comment by amritansh22** [comment]
Please star this repository to show your support, in the meantime I am reviewing your code.

**Comment by ishi0301** [comment]
@amritansh22 done.

**Comment by amritansh22** [comment]
All these commits will be counted as a single PR in hactoberfest. Are you sure to merge them

**Comment by ishi0301** [comment]
I didn't understand. I mean as I have been assigned 4 issues. So all the 4 together will be counted as a single pr in hacktoberfest?

**Comment by ishi0301** [comment]
Please don't merge my pr. I will make 4 different PR from different branches. @amritansh22

**Comment by ishi0301** [comment]
closed

**Pull request closed without merging**
