### PR TITLE
Added Subset sum Solution

### PR DESCRIPTION
**Pull request by deytulsi18**
added the solution to subset sum problem.

### CODE REVIEW

**Comment by deytulsi18** [comment]
How to contribute:

- [ ] Fork this repository
- [ ] Pick up an algorthim
- [ ] Write your code
- [ ] Create a pull request
- [ ] Star the repository to show your support

I have understood and followed the guide lines.

**Comment by deytulsi18** [comment]
Kindly merge the PR

**Comment by amritansh22** [comment]
Excellent work @deytulsi18 Thanks a lot for making this PR.

**Comment by deytulsi18** [comment]
Thank you so much

**Pull request merged**
