### PR TITLE
Newton Raphson Algorithm  for square root

### PR DESCRIPTION
**Pull request by Prakash5bisht**
This algorithm uses Newton Raphson method to calculate square root of a positive integer. In addition to square root you can calculate rth root of a positive integer also. To do so i have provided proper documentation to modify the formula accordingly.

### CODE REVIEW

**Comment by amritansh22** [comment]
Please star this repository to show your support, in the meantime I am reviewing your code.

**Comment by Prakash5bisht** [comment]
Hey, have you reviewed this PR?

**Comment by amritansh22** [comment]
@Prakash5bisht Please star this repository to show your support, in the meantime I am reviewing your code.

**Comment by Prakash5bisht** [comment]
Yep, I  already showed my support.

**Pull request merged**
