### PR TITLE
Added Matrix Chain Multiplication code in C++

### PR DESCRIPTION
**Pull request by joyeta148**

### CODE REVIEW

**Comment by amritansh22** [comment]
Please star this repository to show your support, in the meantime I am reviewing your code.

**Comment by joyeta148** [comment]
> Please star this repository to show your support, in the meantime I am reviewing your code.

okkk sure

**Comment by joyeta148** [comment]
@amritansh22 have you reviewed my code???

**Comment by amritansh22** [comment]
@joyeta148 I am reviewing in the order the contributors have starred the repo. I haven't came till this now.

**Comment by joyeta148** [comment]
@amritansh22 i have stared your repo, still my code haven't been reviewed yet..

**Comment by joyeta148** [comment]
@amritansh22 Please add the hacktoberfest-accepted label too.
As the condition says that,
" A maintainer can accept your PR by merging it, adding the "hacktoberfest-accepted" label to it, or approving it. "

**Comment by amritansh22** [comment]
Approved by a maintainer or labeled as hacktoberfest-accepted.

**Comment by amritansh22** [comment]
This is the official rule updated Yesterday

**Comment by joyeta148** [comment]
@amritansh22 but you have just merged my code.
According to the new rule-
" A maintainer can accept your PR by merging it, adding the "hacktoberfest-accepted" label to it, or approving it. "
It says after merging the maintaner has to approve the code or add the  "hacktoberfest-accepted" label to it.
So, can you please add the  "hacktoberfest-accepted" label to my PR?

**Comment by amritansh22** [comment]
@joyeta148 I already added the label in the afternoon.

**Comment by amritansh22** [comment]
@joyeta148 I have added them

**Comment by amritansh22** [comment]
The rule says that either I have to add hacktoberfest accepted label or approve it. When I merge PR, it means that I have approved it.

**Comment by joyeta148** [comment]
Okay thank you @amritansh22

**Pull request merged**
