### PR TITLE
Matrix Diagonal Sum 

### PR DESCRIPTION
**Pull request by nischalsoni**
**Refer to issue #206 for the problem statement**

### CODE REVIEW

**Comment by amritansh22** [comment]
Are toy opening this for hactoberfest. If so then I think all these commits would count as a single pull request. Should I merge them ??

**Comment by nischalsoni** [comment]
@amritansh22 I checked the website, these all requests have been counted separately, so don't merge them.

**Comment by amritansh22** [comment]
@nischalsoni I am sorry didn't saw this message. I merged the other two. Do you want me revert them back

**Comment by nischalsoni** [comment]
@amritansh22 no no, let it be.

**Pull request merged**
