### PR TITLE
Inorder traversal first commit

### PR DESCRIPTION
**Pull request by Shwetank14**
Inorder traversal of a Binary Tree

### CODE REVIEW

**Comment by amritansh22** [comment]
Please star this repository to show your support, in the meantime I am reviewing your code.

**Comment by Shwetank14** [comment]
> 
> 
> Please star this repository to show your support, in the meantime I am reviewing your code.

Yes I have starred It

**Comment by amritansh22** [comment]
Excellent work @Shwetank14  Thanks a lot for making this PR.

**Comment by Shwetank14** [comment]
Thank you for accepting this PR.
I hope to contribute more.

Thanks a lot aagin

**Pull request merged**
