### PR TITLE
Calculator in C++

### PR DESCRIPTION
**Pull request by mirajkarsaurabh**

### CODE REVIEW

**Comment by amritansh22** [comment]
You have pulled all your commits into this Pull Request. If I merge this I would have to close others(439,437,441,437).
**Do you want me to continue or you would open separate PR's for all the commits.**

**Comment by mirajkarsaurabh** [comment]
Please merge them as individual PR's and NOT as a single PR.
Thanks in advance.

**Comment by amritansh22** [comment]
This is not possible. You have to open separate PR for them or revert commits in individual PR's

**Comment by mirajkarsaurabh** [comment]
Okay i'll open separate PR's. For now you can merge them and close the
others as you have mentioned before.

**Comment by mirajkarsaurabh** [comment]
Are you going to merge them? Like let me know if there are any corrections or any changes to be made.

**Comment by amritansh22** [comment]
@mirajkarsaurabh All your code files are in .txt format, please change them to c++

**Pull request merged**
