### PR TITLE
Maximum circular subarray sum

### PR DESCRIPTION
**Pull request by mendoza**

### CODE REVIEW

**Comment by amritansh22** [comment]
Please star this repository to show your support, in the meantime I am reviewing your code.

**Comment by mendoza** [comment]
> Please star this repository to show your support, in the meantime I am reviewing your code.

Sorry I thought I had done it before, I just starred the repo

**Comment by mendoza** [comment]
Where you able to take a look at it?

**Comment by amritansh22** [comment]
Excellent work @mendoza This is the best PR that I have reviewed till now. The code was properly written and formatted with appropriate variable names and comments Thanks a lot for contributing.

**Comment by mendoza** [comment]
Thank you so much for the compliment, I love this kind of projects so I wanted to make like it was done for me hahaha

**Pull request merged**
