### PR TITLE
Create Best_time_to_buy_stock_and_sell.cpp

### PR DESCRIPTION
**Pull request by sudesh-p**
Added Solution to the Problem 121 of LeetCode "Best Time to Buy and Sell Stock" in C++.

### CODE REVIEW

**Comment by amritansh22** [comment]
Please star this repository to show your support, in the meantime I am reviewing your code.

**Comment by sudesh-p** [comment]
Sure

**Comment by amritansh22** [comment]
Excellent work @sudesh-p  Thanks a lot for making this PR.

**Comment by sudesh-p** [comment]
It's my Pleasure.. looking forward to more meaningful commits.

**Comment by amritansh22** [comment]
Yes sure @sudesh-p

**Pull request merged**
