### PR TITLE
palindrome

### PR DESCRIPTION
**Pull request by ishi0301**

### CODE REVIEW

**Comment by ishi0301** [comment]
@amritansh22 please have a look at my pr.

**Comment by amritansh22** [comment]
@ishi0301 Can you please verify me that your previous pull requests incremented the count of pull requests opened by you on Hactoberfest dashboard

**Comment by ishi0301** [comment]
Yes it's showing on the hacktoberfest dashboard. But i closed my pr. So after 7 days it will automatically be declared null. So this might be counted. @amritansh22

**Comment by amritansh22** [comment]
Okay I am merging this PR and tell me if count is incremented.

**Comment by ishi0301** [comment]
Okay @amitsaini4556 thank you.

**Pull request merged**
