### PR TITLE
Create LCA in Binary Tree

### PR DESCRIPTION
**Pull request by Ashish-kumar7**

### CODE REVIEW

**Comment by Ashish-kumar7** [comment]
@amritansh22 please review this...

**Comment by amritansh22** [comment]
Please star this repository to show your support, in the meantime I am reviewing your code.

**Comment by Ashish-kumar7** [comment]
@amritansh22  done

**Comment by amritansh22** [comment]
Excellent work @Ashish-kumar7 Thanks a lot for making this PR.

**Pull request merged**
