### PR TITLE
created covid and cousin problem

### PR DESCRIPTION
**Pull request by himanshu007-creator**

### CODE REVIEW

**Comment by amritansh22** [comment]
please add a solution file too.

**Comment by himanshu007-creator** [comment]
> please add a solution file too.

ok

**Comment by amritansh22** [comment]
There are some unresolvable conflicts. Please open this PR again.

**Comment by himanshu007-creator** [comment]
> There are some unresolvable conflicts. Please open this PR again.

can you guide me how to do that? do i have to send pull request again?!

**Comment by amritansh22** [comment]
Yes it means you have to send pull request again. But don't worry now, you have already done.

**Pull request closed without merging**
