### PR TITLE
Create finding a perfect number

### PR DESCRIPTION
**Pull request by prashantkumarved**
To find that a given number is a perfect number or not

### CODE REVIEW

**Comment by prashantkumarved** [comment]
> Thanks for opening this pull request! Please be sure that you have checked out our contributing guidelines.

you're welcome, yeah I have checked out.

**Comment by amritansh22** [comment]
Please star this repository to show your support, in the meantime I am reviewing your code.

**Comment by prashantkumarved** [comment]
> Please star this repository to show your support, in the meantime I am reviewing your code.

Done ,Okay you check

**Comment by prashantkumarved** [comment]
> Congrats on merging your first pull request! We are proud of you!

Thankyou

**Pull request merged**
