### PR TITLE
Added find nCr #194

### PR DESCRIPTION
**Pull request by MisterSingh**

### CODE REVIEW

**Comment by amritansh22** [comment]
Since this is unoptimized, you can rename the file and add unoptimized in beginning then I will merge it.

**Comment by MisterSingh** [comment]
@amitsaini4556  Updated the fileName

**Comment by MisterSingh** [comment]
@amritansh22  Any updates on this ?

**Comment by amritansh22** [comment]
Please star this repository to show your support, in the meantime I am reviewing your code.

**Pull request closed without merging**
