### PR TITLE
Added K'th Largest Element in an array 

### PR DESCRIPTION
**Pull request by anjali1102**
@amritansh22 you assigned me here

### CODE REVIEW

**Comment by anjali1102** [comment]
pls check my PR @amritansh22

**Comment by amritansh22** [comment]
Please star this repository to show your support, in the meantime I am reviewing your code.

**Comment by anjali1102** [comment]
Done @amritansh22

**Comment by amritansh22** [comment]
Excellent work @anjali1102 Thanks a lot for making this PR.

**Comment by anjali1102** [comment]
@amritansh22 pls.add hactober accepted label in #167

**Comment by anjali1102** [comment]
@amritansh22 I mean "hacktober-accepted" label on my #167  else it won't be count further.

**Comment by amritansh22** [comment]
@anjali1102 Is this PR not counted on hacktoberfest homepage ??

**Comment by anjali1102** [comment]
@amritansh22 today on their website they have said that PR merged with "hacktober-accepted" label will be eligible....

**Pull request merged**
