### PR TITLE
Create Coins_Denomination.cpp

### PR DESCRIPTION
**Pull request by Bijoy-007**
Please review and add this after 1st oct

### CODE REVIEW

**Comment by Bijoy-007** [comment]
review

**Comment by Bijoy-007** [comment]
Please review this and  inform me if something needs to be changed

**Comment by amritansh22** [comment]
Everything looks fine

**Comment by amritansh22** [comment]
Although you have 2 files in this PR however, it will be counted as 1 only PR in hactoberfest as it does not count number of files committed to but pull requests opened

**Comment by Bijoy-007** [comment]
Ok so can I cancel this one ? commit 1 again then afer accepting I'll commit Another one

**Comment by Bijoy-007** [comment]
ok i am opening again

**Comment by Bijoy-007** [comment]
a new one

**Pull request closed without merging**
