### PR TITLE
matrix multiplication without function

### PR DESCRIPTION
**Pull request by hustlesid**

### CODE REVIEW

**Comment by hustlesid** [comment]
@amritansh22 please review the code and merge the code and also add the hacktoberfest accepted label

**Comment by amritansh22** [comment]
Please star this repository to show your support, in the meantime I am reviewing your code.

**Comment by hustlesid** [comment]
Okk,Amritansh doing

**Comment by hustlesid** [comment]
@amritansh22 ,please add the hacktoberfest accepted labe;

**Comment by amritansh22** [comment]
@hustlesid No need for it

**Pull request merged**
